apiVersion: apps/v1
kind: Deployment
metadata:
  name: kz-prod-flask-deployment
  labels:
    app: kz-prod-flask
    username: kz
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kz-prod-flask
  template:
    metadata:
      labels:
        app: kz-prod-flask
        username: kz
        env: prod
    spec:
      containers:
        - name: kz-prod-api
          imagePullPolicy: Always
          image: zoeclairewatson/final:latest
          command: ["python", "api.py"]
          env:
          - name: FLASK_APP
            value: "api.py"
          - name: REDIS_IP
            value: "10.105.20.241"
          ports:
          - name: http
            containerPort: 5000
