---
apiVersion: v1
kind: Service
metadata:
  name: kz-prod-flask-service
  labels:
    app: kz-prod-flask
    username: kz
    env: prod
spec:
  type: ClusterIP
  selector:
    app: kz-prod-flask
  ports:
  - name: kz-prod-flask-service
    port: 5000
    targetPort: 5000 
