---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kz-prod-pvc-data
  labels:
    username: kz
    env: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
