---
apiVersion: v1
kind: Service
metadata:
  name: kz-prod-redis-service
  labels:
    app: kz-prod-redis
    username: kz
    env: prod
spec:
  type: ClusterIP
  selector:
    app: kz-prod-redis
  ports:
  - name: kz-prod-redis-service
    port: 6379
    targetPort: 6379
