version: '3'

services:

    web:
        build: .
        container_name: zoe_web
        ports:
            - 5037:5000
        volumes:
            - ./data/animals_data.json:/data_file.json

    redis:
        image: redis:latest
        ports:
            - 6417:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: ["redis-server", "/redis.conf"]
