---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zcw268-test-pvc-data
  labels:
    username: zcw268
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
